name: Generate Markdown

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:        
      - docs

jobs:
  generate_markdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check for specific label
      id: label-check
      run: |
        echo '${{ toJson(github.event.pull_request.labels) }}' > labels.json
        LABEL=$(jq -r '.[] | select(.name == "docs") | .name' labels.json)
        if [ "$LABEL" == "docs" ]; then
          echo "Label 'docs' found."
          echo "label_present=true" >> $GITHUB_ENV
        else
          echo "Label 'docs' not found."
          echo "label_present=false" >> $GITHUB_ENV
        fi

    - name: Run Job if Label is Present
      if: env.label_present == 'true'
      run: |
        echo "Running job because 'docs' label is present on the merged pull request."

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML

    - name: Generate Markdown
      run: |
        python .github/generate_markdown.py

    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: markdown-artifact
        path: .github/output.md

    - name: Trigger Repository Dispatch
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.CROSS_REPO_TRIGGER }}" \
          https://api.github.com/repos/thutuva/copy-docs/dispatches \
          -d '{"event_type": "triggered_from_repo_a"}'
