name: Generate Markdown

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate_markdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML

    - name: Generate Markdown
      run: |
        python .github/generate_markdown.py

    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: markdown-artifact
        path: .github/output.md

    - name: Dispatch event to trigger second repository
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GENERATE_MARKDOWN_TOKEN }}
        event-type: trigger-second-repo
        client-payload: '{"repository": "personal-tuva-docs"}'
